"""Generates the animated README graphics (progress.svg and terminal.svg) next to this file.

Solved a few more problems? Change SOLVED below and run:  python assets/make_svgs.py
Only the standard library is used.
"""
from pathlib import Path
from xml.sax.saxutils import escape

SOLVED, GOAL = 68, 100
OUT = Path(__file__).resolve().parent

MONO = "'Cascadia Code', Consolas, 'SF Mono', Menlo, 'DejaVu Sans Mono', monospace"
SANS = "'Segoe UI', Ubuntu, 'Helvetica Neue', Arial, sans-serif"
NOTE = "<!-- generated by assets/make_svgs.py, edit SOLVED there and re-run instead of editing this file -->"

# ------------------------------------------------------------------ terminal
LOOP = 15.0  # seconds for one full play-through, then it restarts
lines = [
    # (segments[(text, color)], reveal_start_s, reveal_duration_s)
    ([("$ ", "#C4B5FD"), ("python grind.py", "#e6edf3")], 0.6, 1.6),
    ([("› ", "#A78BFA"), ("loading motivation ........ ", "#A89CC8"), ("done ✅", "#C4B5FD")], 2.8, 1.0),
    ([("› ", "#A78BFA"), ("problems solved: ", "#A89CC8"), (f"{SOLVED} / {GOAL} 🔥", "#C4B5FD")], 4.0, 0.8),
    ([("› ", "#A78BFA"), ("bugs squashed: ", "#A89CC8"), ("too many to count 🐛", "#e6edf3")], 5.0, 0.9),
    ([("› ", "#A78BFA"), ("sleep schedule: ", "#A89CC8"), ("404 not found 😴", "#DDD6FE")], 6.1, 0.9),
    ([("› ", "#A78BFA"), ("status: ", "#A89CC8"), ("LOCKED IN 🔒", "#C4B5FD")], 7.2, 0.8),
    ([("$ ", "#C4B5FD")], 8.4, 0.1),
]
W, TOP, LH, X0, CH = 800, 78, 32, 32, 10.2  # CH: generous monospace advance at 17px
H = TOP + LH * (len(lines) - 1) + 30

parts = [f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-label="Terminal: problems solved {SOLVED} of {GOAL}, status locked in">
  {NOTE}
  <defs>''']
for i, (segs, start, dur) in enumerate(lines):
    width = sum(len(t) for t, _ in segs) * CH + 50
    a, b = start / LOOP, (start + dur) / LOOP
    parts.append(f'''    <clipPath id="l{i}"><rect x="{X0}" y="{TOP + LH * i - 24}" height="{LH}" width="0">
      <animate attributeName="width" values="0;0;{width:.0f};{width:.0f}" keyTimes="0;{a:.4f};{b:.4f};1" dur="{LOOP}s" repeatCount="indefinite"/>
    </rect></clipPath>''')
parts.append(f'''  </defs>
  <rect x="0.5" y="0.5" width="{W - 1}" height="{H - 1}" rx="12" fill="#140f1f" stroke="#2d2440"/>
  <circle cx="26" cy="22" r="6.5" fill="#7C3AED"/><circle cx="48" cy="22" r="6.5" fill="#A78BFA"/><circle cx="70" cy="22" r="6.5" fill="#DDD6FE"/>
  <text x="{W / 2}" y="27" text-anchor="middle" font-family="{SANS}" font-size="13" fill="#A89CC8">zsh : ~/python-100</text>
  <line x1="0" y1="42" x2="{W}" y2="42" stroke="#241b36"/>
  <g font-family="{MONO}" font-size="17">
    <animate attributeName="opacity" values="1;1;0;0" keyTimes="0;0.93;0.97;1" dur="{LOOP}s" repeatCount="indefinite"/>''')
for i, (segs, start, dur) in enumerate(lines):
    spans = "".join(f'<tspan fill="{c}">{escape(t)}</tspan>' for t, c in segs)
    y = TOP + LH * i
    extra = ""
    if i == len(lines) - 1:  # blinking cursor after the final prompt
        extra = (f'<rect x="{X0 + 2 * CH + 2:.0f}" y="{y - 15}" width="10" height="19" fill="#e6edf3">'
                 f'<animate attributeName="opacity" values="1;0" dur="1s" calcMode="discrete" repeatCount="indefinite"/></rect>')
    parts.append(f'    <g clip-path="url(#l{i})"><text x="{X0}" y="{y}" xml:space="preserve">{spans}</text>{extra}</g>')
parts.append("  </g>\n</svg>\n")
(OUT / "terminal.svg").write_text("\n".join(parts), encoding="utf-8", newline="\n")

# ------------------------------------------------------------------ progress bar
PW, PH, BX, BY, BW, BH = 800, 160, 40, 100, 720, 18
fill = round(BW * SOLVED / GOAL)
progress = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{PW}" height="{PH}" viewBox="0 0 {PW} {PH}" role="img" aria-label="Road to {GOAL}: {SOLVED} of {GOAL} problems solved">
  {NOTE}
  <defs>
    <linearGradient id="bar" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#8B5CF6"/><stop offset="1" stop-color="#C4B5FD"/>
    </linearGradient>
    <linearGradient id="shine" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#ffffff" stop-opacity="0"/>
      <stop offset="0.5" stop-color="#ffffff" stop-opacity="0.6"/>
      <stop offset="1" stop-color="#ffffff" stop-opacity="0"/>
    </linearGradient>
    <clipPath id="fill"><rect x="{BX}" y="{BY}" height="{BH}" rx="{BH / 2}" width="0">
      <animate attributeName="width" values="0;{fill}" keyTimes="0;1" calcMode="spline" keySplines="0.22 1 0.36 1" begin="0.4s" dur="2.4s" fill="freeze"/>
    </rect></clipPath>
  </defs>
  <rect x="0.5" y="0.5" width="{PW - 1}" height="{PH - 1}" rx="16" fill="#140f1f" stroke="#2d2440"/>
  <text x="{BX}" y="38" font-family="{SANS}" font-size="12" font-weight="700" letter-spacing="3" fill="#C4B5FD">ROAD TO {GOAL}</text>
  <text x="{BX}" y="74" font-family="{SANS}" fill="#e6edf3"><tspan font-size="34" font-weight="800">{SOLVED}</tspan><tspan font-size="20" fill="#A89CC8"> / {GOAL}</tspan><tspan font-size="16" fill="#A89CC8" dx="10">problems cooked 🔥</tspan></text>
  <text x="{BX + BW}" y="74" text-anchor="end" font-family="{SANS}" font-size="15" fill="#A89CC8">{GOAL - SOLVED} to go. we move 🚀</text>
  <rect x="{BX}" y="{BY}" width="{BW}" height="{BH}" rx="{BH / 2}" fill="#241b36"/>
  <g clip-path="url(#fill)">
    <rect x="{BX}" y="{BY}" width="{fill}" height="{BH}" fill="url(#bar)"/>
    <rect x="-160" y="{BY}" width="160" height="{BH}" fill="url(#shine)">
      <animate attributeName="x" values="-160;{BX + fill}" begin="2.8s" dur="2.2s" repeatCount="indefinite"/>
    </rect>
  </g>
  <text y="{BY - 6}" font-size="22" x="{BX - 14}">🐍
    <animate attributeName="x" values="{BX - 14};{BX + fill - 14}" keyTimes="0;1" calcMode="spline" keySplines="0.22 1 0.36 1" begin="0.4s" dur="2.4s" fill="freeze"/>
    <animateTransform attributeName="transform" type="translate" values="0 0;0 -4;0 0" begin="2.8s" dur="0.8s" repeatCount="indefinite"/>
  </text>
  <text x="{BX}" y="{BY + 44}" font-family="{MONO}" font-size="13" fill="#7A6F99">print("hello world")</text>
  <text x="{BX + BW}" y="{BY + 44}" text-anchor="end" font-family="{SANS}" font-size="13" fill="#7A6F99">interview ready 💼</text>
</svg>
'''
(OUT / "progress.svg").write_text(progress, encoding="utf-8", newline="\n")
print(f"wrote {OUT / 'terminal.svg'} and {OUT / 'progress.svg'} ({SOLVED}/{GOAL})")
